name: Monitor Third-Party Repository

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Copy files from repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Check latest commit on third-party repository
        id: check_commit
        run: |
          REPO="getumbrel/umbrel-apps"
          API_URL="https://api.github.com/repos/$REPO/commits/main"
          echo "Checking for updates in $REPO"
          
          LAST_COMMIT=$(curl -s $API_URL | jq -r '.sha')
          echo "Last commit in the third repository: $LAST_COMMIT"
          
          CACHE_FILE=".last_commit"
          if [ -f "$CACHE_FILE" ]; then
            PREVIOUS_COMMIT=$(cat "$CACHE_FILE")
          else
            PREVIOUS_COMMIT=""
          fi
          
          echo "$LAST_COMMIT" > "$CACHE_FILE"

          if [ "$LAST_COMMIT" == "$PREVIOUS_COMMIT" ]; then
            echo "No updates found."
            echo "updated=false" >> $GITHUB_ENV
          else
            echo "New commit detected: $LAST_COMMIT"
            echo "updated=true" >> $GITHUB_ENV
          fi

      - name: Run Python script if updated
        if: env.updated == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
          poetry run python cutp/utils/gen.py
          poetry run task format

      - name: Configure Git
        if: env.updated == 'true'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Check for changes
        id: check_changes
        run: |
            if git diff --quiet; then
                echo "No changes detected."
                echo "changes_detected=false" >> $GITHUB_ENV
            else
                echo "Changes detected."
                echo "changes_detected=true" >> $GITHUB_ENV
            fi
    
      - name: Commit changes
        if: env.changes_detected == 'true'
        run: |
            git add .
            git commit -m "Updates based on getumbrel/umbrel-apps"

      - name: Create Pull Request
        if: env.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Updates based on getumbrel/umbrel-apps"
          title: "Updating list of occupied TCP ports"
          body: "This PR contains updates based on changes detected in `getumbrel/umbrel-apps`."
